version: '3'

services:
  app:
    image: php:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
    - "8081:8000"
    networks:
      - laravel
    depends_on:
      - database
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=laraveluser"
      - "DB_PASSWORD=laravelpassword"
    command: ["php", "artisan", "serve", "--host=0.0.0.0"]

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - laravel

networks:
  laravel:

